In [1]:

import numpy as np

array=np.array([1,2,3,4,5])
print(array)  








[1 2 3 4 5]


In [ ]:
#to find dimesions

array=np.array([1,2,3,4,5])
print(array,array.ndim)




[1 2 3 4 5] 1


In [ ]:
#to find value, size 

array=np.array([1,2,3,4,5])
print(array,array.ndim,array.size)



[1 2 3 4 5] 1 5


In [ ]:
# to find shape  

array=np.array([1,2,3,4,5])
print(array,array.ndim,array.shape)


[1 2 3 4 5] 1 (5,)


In [ ]:
#dimensions 
#import numpy as np
##array=np.array([1,2,3,4,5])
#print(array,array.ndim,array.shape,array.dtype)




In [12]:
import pandas as pd 

data= {
    'visitors':[100,200,300,400,500,450,720,120,540,320],
'sales':[1125,4400,9000,5000,3400,6000,3300,8000,3400,12000]

}

df=pd.DataFrame(data)


In [13]:
df

visitors  sales
0       100   1125
1       200   4400
2       300   9000
3       400   5000
4       500   3400
5       450   6000
6       720   3300
7       120   8000
8       540   3400
9       320  12000

In [14]:
df=pd.read_csv("data.csv")

df

visitors:[100   200   300   400   500   450   720   120   540    320]
0   sales:[1125  4400  9000  5000  3400  6000  3300  8000  3400  12000]

In [17]:
import sys
import pandas as pd 
import matplotlib.pyplot as plt

df=pd.read_csv("data.csv")

In [18]:
df 

visitors:[100   200   300   400   500   450   720   120   540    320]
0   sales:[1125  4400  9000  5000  3400  6000  3300  8000  3400  12000]

In [4]:
df.plot()

plt.savefig("output.png")

sys.stdout.flush()


NameError: name 'df' is not defined